# Generated by Django 4.2.1 on 2023-06-21 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0017_cliente_password_alter_cliente_fecha_alta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 21, 16, 12, 51, 105295, tzinfo=datetime.timezone.utc), verbose_name='Fecha de alta'),
        ),
    ]
