# Generated by Django 4.2.1 on 2023-06-21 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0019_alter_cliente_fecha_alta_mascota_historiaclinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 21, 17, 24, 14, 845945, tzinfo=datetime.timezone.utc), verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_consulta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 21, 17, 24, 14, 845945, tzinfo=datetime.timezone.utc), verbose_name='Fecha de consulta'),
        ),
    ]
