# Generated by Django 4.2.1 on 2023-06-22 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0023_alter_cliente_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='tipo_mascota',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de mascota'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 22, 16, 17, 58, 369533, tzinfo=datetime.timezone.utc), verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_consulta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 22, 16, 17, 58, 370541, tzinfo=datetime.timezone.utc), verbose_name='Fecha de consulta'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo_mascota',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de mascota'),
        ),
    ]
